# Uncomment the next line to define a global platform for your project
platform :macos, '10.7'

target 'SwiftPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks! :linkage => :static
  pod 'mdk'
  # Pods for SwiftPlayer
end

