name: Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  macOS:
    runs-on: macos-14
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
#    - run: flutter config --enable-macos-desktop
    - run: flutter doctor --verbose
    - run: flutter pub get
      working-directory: flutter/simple
    - run: flutter build macos --verbose
      working-directory: flutter/simple
    - run: |
        mv build/macos/Build/Products/Release/simple.app .
        cmake -E tar cvf flutter_example_macos.7z --format=7zip simple.app
      working-directory: flutter/simple
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: examples-macOS
        path: flutter/simple/flutter_example_macos.7z

  Windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        channel: ['stable']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: subosito/flutter-action@v2
      with:
        channel: ${{ matrix.channel }}
        cache: true
    - run: flutter doctor --verbose
    - run: flutter pub get
      working-directory: flutter/simple
    - run: flutter build windows --verbose
      working-directory: flutter/simple
    - run: |
        mv build/windows/x64/runner/Release .
        cmake -E tar cvf flutter_example_windows-${{ matrix.channel }}.7z --format=7zip Release
      working-directory: flutter/simple
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: example-windows-${{ matrix.channel }}
        path: |
          flutter/simple/flutter_example_windows-${{ matrix.channel }}.7z

  Linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['any']
        channel: ['stable']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.version }}
        channel: ${{ matrix.channel }}
        cache: true
    - run: |
       sudo apt-get update -y
       sudo apt-get install -y cmake clang ninja-build libgtk-3-dev libpulse-dev
#    - run: flutter config --enable-linux-desktop
    - run: flutter doctor --verbose
    - run: flutter pub get
      working-directory: flutter/simple
    - run: flutter build linux --verbose
      working-directory: flutter/simple
    - run: |
        mv build/linux/x64/release/bundle .
        cmake -E tar Jcvf flutter_example_linux-${{ matrix.channel }}-${{ matrix.version }}.tar.xz bundle
      working-directory: flutter/simple
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build CMake Projects
      run: |
        ls ~/.pub-cache/hosted/pub.dev/fvp*/linux
        cp ~/.pub-cache/hosted/pub.dev/fvp*/linux/mdk-sdk-linux.tar.xz .
        tar xvf mdk-sdk-linux.tar.xz
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -S ${{ github.workspace }} -DCMAKE_INSTALL_PREFIX=install
        cmake --build build --config RelWithDebInfo
        cmake --install build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: example-linux-${{ matrix.channel }}-${{ matrix.version }}
        path: |
            flutter/simple/flutter_example_linux*.tar.xz
            install

  Android:
    runs-on: ${{ matrix.host }}-latest
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - run: flutter doctor --verbose
    - run: flutter pub get
      working-directory: flutter/simple
    - run: flutter build apk --verbose
      working-directory: flutter/simple
    - run: |
        mv ./build/app/outputs/apk/release/app-release.apk flutter_example_android.apk
      working-directory: flutter/simple
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: example-android-${{ matrix.host }}
        path: flutter/simple/flutter_example_android.apk
